### PR TITLE
Poster📰 - Joint Face Detection and Alignment using Multi-task Cascaded …

### PR DESCRIPTION
**Pull request by Jarvisgivemeasuit**
# AMC Seminar Sign Up

> Link to previous seminar meeting minutes issue:

#129 

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:
>
> 1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q/A.
> 1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.

- [ ] 🗣 Oral (15 MIN)
- [x] 📰 Poster (5 MIN)

## 2. Paper Information

> Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)

| Paper | Information |
| --- | --- |
| Name | Joint Face Detection and Alignment using Multi-task Cascaded Convolutional Networks |
| Year | 2016 |
| Publish | IEEE Signal Processing Letters 2016 |
| Author | Zhang, et. al. |
| GitHub | https://github.com/kpzhang93/MTCNN_face_detection_alignment |
| Blog | https://kpzhang93.github.io/MTCNN_face_detection_alignment/ |
| Arxiv | https://arxiv.org/abs/1604.02878 |

### 3. After Party 🍻

> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can expect that it will be related to meeting topics of the day)
> 1. The bill will be paid AA

- [ ] 🍻 YES! I'll definitely join the After Party!
- [x] 🤔 Maybe. I'd like to decide later.
- [ ] 🛌 No, I'm afraid not this time.

## 4. New Friend

> Whether you have a new friend comes with you to the club.

- [ ] 👥 I'll bring a new friend
- [x] 👤 There's no new friend from me

----------------
<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://github.com/BUPT/ai-ml.club/wiki/Member-Manual">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by huan** [comment]
MTCNN, one of my favourite!

**Comment by cgpeter96** [comment]
抱歉，远程库和提交的pr有些不同，请重写git pull upstream master，然后重新push一下

**Comment by huan** [comment]
I hope this PR could be able to be merged soon.

Let's keep our PR queue clean, thanks!

**Comment by linbo0518** [comment]
I resolved the conflict, everybody can merge after code review

**Pull request merged**
