### PR TITLE
Poster📰 - A Dual Reinforcement Learning Framework for Unsupervised Text Style Transfer, Fuli Luo et. al., ACL2019

### PR DESCRIPTION
**Pull request by huan**
# AMC Seminar Sign Up

> Link to previous seminar meeting minutes issue:

#129 

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:
>
> 1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q/A.
> 1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.

- [ ] 🗣 Oral (15 MIN)
- [x] 📰 Poster (5 MIN)

## 2. Paper Information

> Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)

| Paper | Information |
| --- | --- |
| Name | A Dual Reinforcement Learning Framework for Unsupervised Text Style Transfer  |
| Year | 2019 |
| Publish | ACL |
| Author | Fuli Luo et. al. |
| GitHub | https://github.com/luofuli/DualRL  |
| Blog | https://weibo.com/2678093863/HyxQaDFDK |
| Arxiv | https://export.arxiv.org/pdf/1905.10060 |

### 3. After Party 🍻

> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can expect that it will be related to meeting topics of the day)
> 1. The bill will be paid AA

- [x] 🍻 YES! I'll definitely join the After Party!
- [ ] 🤔 Maybe. I'd like to decide later.
- [ ] 🛌 No, I'm afraid not this time.

## 4. New Friend

> Whether you have a new friend comes with you to the club.

- [x] 👥 I'll bring a new friend

Please fill the following table for the new friend sign up(if any), or delete it.

| Referrer | Newcomer  | Bio |
| -------- | --------- | --- |
| @huan  | @newip | Robotics Startup founder, Electronic and Information Tech researcher. |

----------------
<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://github.com/BUPT/ai-ml.club/wiki/Member-Manual">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by CyFeng16** [comment]
@huan The blog link seems to be broken. Can you double-check it?

**Comment by huan** [comment]
image

I can visit it without any problem.

**Comment by CyFeng16** [comment]
@huan Sorry about that. I can't access it because my Weibo doesn't log in automatically.

**Comment by huan** [comment]
Yeah, weibo sucks.

**Comment by CyFeng16** [comment]
@huan Its idea is just like CycleGAN(at https://arxiv.org/pdf/1703.10593.pdf), and in its references, we can see (Unpaired S2S at https://www.semanticscholar.org/paper/c2991c7f3af925e6cb6361522fd7a2f66631a216). 
These give us some speculation about the source thought of the paper.

**Pull request merged**
