### PR TITLE
Change gem source to china

### PR DESCRIPTION
**Pull request by Duan-JM**
For gem source in the `Gemfile` somehow didn't work even connect with VPN, I change it to the source in china, I believe(?) it will be better for most of the members to build the website locally.

### CODE REVIEW

**Comment by CyFeng16** [comment]
It doesn't seem to have a connection problem here, would you re-check it?

**Comment by Duan-JM** [comment]
@CyFeng16 I re-checked it twice, my vpn is built on OD, San Fransico. Maybe this issue only occur in my situation according to the bad network connection. So, feel free to close it, if this issue do not bother other mainters.

**Comment by CyFeng16** [comment]
image

It seems no problem with website connectivity, you may check the local settings.
Please close this issue after reviewing it. :)

**Comment by Duan-JM** [comment]
CleanShot 2019-12-13 at 16 13 07

CleanShot 2019-12-13 at 16 14 35

I insisted there did exist problem with website connectivity and retest the lag.
> Free free to test rubygems.org and test gems.ruby-china.com [here](https://tool.chinaz.com/speedtest/gems.ruby-china.com)
From the figure above, we can see the lag reached 3611ms for rubygems.org, note that this will lead to the low speed to download the requirement packages). Fortunately, for gems.ruby-china.com alleviate this problem significantly.

**Comment by Duan-JM** [comment]
It seems that this problem does not bother the other code maintainers, close it for there is no need to make an effort to change this source for the repo.

**Pull request closed without merging**
