### PR TITLE
Create xinhe.md

### PR DESCRIPTION
**Pull request by newip**
Create XinHe.md file.

### CODE REVIEW

**Comment by linbo0518** [comment]
the author should be 'newip', same as authors.yml

**Comment by newip** [comment]
> Some typos in your file maybe:
> 
> 1. Line 3, `Xin HE (贺新)`-> `Xin He (贺新)`
> 2. Line 15, maybe missing number `  year CS Ph.D`
> 
> @newip

For 1, It is ok for all capital letters for the last name. But also ok as your comment.
For 2, it is my problem to commit an unfinished block.

**Comment by huan** [comment]
I believe the filename should follow the GitHub username.

In this case, it should be newip

**Comment by newcomer** [comment]
Hi There,

I'm getting a lot of emails because you mention my username @newcomer in your PRs.
Could you please stop doing?

Thanks,
Oleg

**Pull request merged**
