### PR TITLE
add vdeamov's personal info

### PR DESCRIPTION
**Pull request by VDeamoV**

### CODE REVIEW

**Comment by VDeamoV** [comment]
> Please help yourself and feel free to merge this PR

Sadly, I don't have the write access to merge the pull requests

**Comment by huan** [comment]
@VDeamoV No problem, please free to ask your chairman to help you adding chair privileges because you had finished your chair duty!

**Comment by VDeamoV** [comment]
@huan okay, I will ask for write access later~ thx

**Comment by huan** [comment]
The CI system works now!

**Pull request merged**
