### PR TITLE
第二季19场 AI ML Club 活动纪要

### PR DESCRIPTION
**Pull request by VDeamoV**
- [x] 尝试嵌入pdf

### CODE REVIEW

**Comment by huan** [comment]
Great to see that you are using `view-js` now!

I believe you will also add a new rule to filenamelint:

```diff
.file-name-linter.json 
{
  "rules": {
    "docs/_posts": [
      "^docs/_posts/",
      "/[0-9\\-a-z]+\\.",
      "\\.md$"
    ],
    "docs/assets": [
      "^docs/assets/",
      "/[0-9\\-a-z]+\\.",
-      "\\.(jpg|png|gif)$"
+     "\\.(jpg|png|gif|pdf)$"
    ]
  },
  "ignore": [
    "docs/assets/js/viewer-js",
    "tests/fixtures"
  ]
}
```

**Comment by huan** [comment]
Great to see that you are using `view-js` now!

I believe you will also add a new rule to filenamelint:

```diff
.file-name-linter.json 
{
  "rules": {
    "docs/_posts": [
      "^docs/_posts/",
      "/[0-9\\-a-z]+\\.",
      "\\.md$"
    ],
    "docs/assets": [
      "^docs/assets/",
      "/[0-9\\-a-z]+\\.",
-      "\\.(jpg|png|gif)$"
+     "\\.(jpg|png|gif|pdf)$"
    ]
  },
  "ignore": [
    "docs/assets/js/viewer-js",
    "tests/fixtures"
  ]
}
```

**Comment by huan** [comment]
Great to see that you are using `view-js` now!

I believe you will also add a new rule to filenamelint:

```diff
.file-name-linter.json 
{
  "rules": {
    "docs/_posts": [
      "^docs/_posts/",
      "/[0-9\\-a-z]+\\.",
      "\\.md$"
    ],
    "docs/assets": [
      "^docs/assets/",
      "/[0-9\\-a-z]+\\.",
-      "\\.(jpg|png|gif)$"
+     "\\.(jpg|png|gif|pdf)$"
    ]
  },
  "ignore": [
    "docs/assets/js/viewer-js",
    "tests/fixtures"
  ]
}
```

**Comment by linbo0518** [comment]
docs/_posts/2019-07-21-seminar-meeting-minutes-2-19.md: 62: MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "![段嘉铭]({{ '/assets/2019/semina..."]
docs/_posts/2019-07-21-seminar-meeting-minutes-2-19.md: 118: MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "![尹鹏宇]({{ '/assets/2019/semina..."]
docs/_posts/2019-07-21-seminar-meeting-minutes-2-19.md: 171: MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]

You may add a blank line for MD032 and remove the extra blank line for MD012

**Pull request merged**
