### PR TITLE
📰Poster - Real-Time Monocular Pose Estimation of 3D Objects using Temporally Consistent Local Color Histograms

### PR DESCRIPTION
**Pull request by newip**
# AMC Seminar Sign Up

> Link to previous seminar meeting minutes issue:

#164 

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:
>
> 1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q/A.
> 1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.

- [ ] 🗣 Oral (15 MIN)
- [x] 📰 Poster (5 MIN)

## 2. Paper Information

> Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)

| Paper | Information |
| --- | --- |
| Name | Real-Time Monocular Pose Estimation of 3D Objects using Temporally Consistent Local Color Histograms |
| Recommendation | The demo is great for real-time 3D object tracking |
| Year | 2017 |

### 3. After Party 🍻

> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can expect that it will be related to meeting topics of the day)
> 1. The bill will be paid AA

- [ ] 🍻 YES! I'll definitely join the After Party!
- [ ] 🤔 Maybe. I'd like to decide later.
- [x] 🛌 No, I'm afraid not this time.

## 4. New Friend

> Whether you have a new friend comes with you to the club.

- [x] 👥 I'll bring a new friend
- [ ] 👤 There's no new friend from me

Please fill the following table for the new friend sign up(if any), or delete it.

| Referrer | Newcomer  | Bio |
| -------- | --------- | --- |
| @newip  | @gaojiuy | 北邮经管院研一的高久怡，研究方向是CNN可视化 |

----------------
<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://ai-ml.club/manuals/member/">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by Jarvisgivemeasuit** [comment]
Can you add a arxiv or blog link? 😃

**Comment by newip** [comment]
> Can you add a arxiv or blog link? 😃

https://arxiv.org/abs/1807.02087
只找到同一作者的这一篇，title不同，还不确定是不是相同的内容。

http://openaccess.thecvf.com/content_iccv_2017/html/Tjaden_Real-Time_Monocular_Pose_ICCV_2017_paper.html
实际是这一篇，这个ICCV的链接是不是也可以用？

**Comment by Jarvisgivemeasuit** [comment]
that's Ok, thank you.😃

**Comment by fuyunfuyun666** [comment]
师兄，能挂靠一下吗

**Pull request merged**
