### PR TITLE
🗣Oral  - The Evaluation of Chinese Human-Computer Dialogue Technology,SMP2019-ECDT

### PR DESCRIPTION
**Pull request by initc**
# AMC Seminar Sign Up

> Link to previous seminar meeting minutes issue:

#201

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:
>
> 1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q/A.
> 1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.

- [x] 🗣 Oral (15 MIN)
- [ ] 📰 Poster (5 MIN)

## 2. Paper Information

> Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)

| Paper | Information |
| --- | --- |
| Name | SMP2019-ECDT |
| Recommendation | Human-Computer Dialogue in practice |
| Prior Knowledge| GPT |
| Year | 2019 |
| Publish | CIPS-SMP |
| Blog | http://conference.cipsc.org.cn/smp2019/evaluation.html |

### 3. After Party 🍻

> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can expect that it will be related to meeting topics of the day)
> 1. The bill will be paid AA

- [ ] 🍻 YES! I'll definitely join the After Party!
- [x] 🤔 Maybe. I'd like to decide later.
- [ ] 🛌 No, I'm afraid not this time.

## 4. New Friend

> Whether you have a new friend comes with you to the club.

- [ ] 👥 I'll bring a new friend
- [x] 👤 There's no new friend from me

Please fill the following table for the new friend sign up(if any), or delete it.

<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://ai-ml.club/manuals/member/">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by huan** [comment]
I love NLP oral!

Looking forward to hearing it! :clap:

**Comment by huan** [comment]
However, I believe you linked to the wrong issue number.

The previous minus issue is #201, not #199 :)

**Comment by huan** [comment]
我申请挂靠胜杰的 Oral 参会 @CyFeng16

**Comment by initc** [comment]
@CyFeng16 申请此PR参加8\11的AMC

**Pull request merged**
