### PR TITLE
poster : Convolutional Pose Machines

### PR DESCRIPTION
**Pull request by houzhenggangGit**
S2E12

Ref: [#107](https://github.com/BUPT/ai-ml.club/issues/107)
Convolutional Pose Machines
Poster

### CODE REVIEW

**Comment by 824zzy** [comment]
For the sake of time limit, we have to leave your poster to next week. Thank you for your great idea about social analysis in brain storm speech. 😊

By the way, please fix the conflict(Resolve conflicts Button) and change your commit comment(S2E12-->S2E13 and so on). @houzhenggangGit

**Comment by cgpeter96** [comment]
你好，这次PR有冲突 建议查看先从upstream 重新拉库，然后重新提交PR

**Comment by huan** [comment]
Can we merge for now because it should be merged before this seminar?

**Comment by huan** [comment]
I merged this PR because it was created before the linting CI requirements and had some trouble to pass them.

**Pull request merged**
