### PR TITLE
关于申请成立AMC学术指导委员会暨MM项目外联工作汇报

### PR DESCRIPTION
**Pull request by secortot**
> Please copy/paste the title template from the following line:
> 📰Poster - 关于申请成立AMC学术指导委员会暨MM项目外联工作汇报

# AMC Seminar Sign Up

> Link to previous seminar meeting minutes comments issue:

#422 

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:
>
> 1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q/A.
> 1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.

- [ ] 🗣 Oral (15 MIN)
- [√] 📰 Poster (5 MIN)

## 2. Paper Information

> Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)

| Paper           | Information                |
| --------------- | -------------------------- |
| Name            | PAPER_NAME                 |
| Recommendation  | ONE_LINE_RECOMMENDATION    |
| Prior Knowledge | KEYWORDS                   |
| Year            | PUBLISH_YEAR               |
| Publish         | CONFERENCE_OR_JOURNAL_NAME |
| Author          | AUTHOR1, et. al.           |
| GitHub          | GITHUB_LINK                |
| Blog            | BLOG_LINK                  |
| Arxiv           | ARXIV_LINK                 |

### 3. After Party 🍻

> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can expect that it will be related to meeting topics of the day)
> 1. The bill will be paid AA

- [ ] 🍻 YES! I'll definitely join the After Party!
- [x] 🤔 Maybe. I'd like to decide later.
- [ ] 🛌 No, I'm afraid not this time.

## 4. New Friend

> Whether you have a new friend comes with you to the club.

- [ ] 👥 I'll bring a new friend
- [x] 👤 There's no new friend from me

Please fill the following table for the new friend sign up(if any), or delete it.

| Referrer | Newcomer  | Bio                    |
| -------- | --------- | ---------------------- |
| @member  | @_NEWCOMER_ | ONE_SENTENCE_BIOGRAPHY |

----------------
<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://ai-ml.club/manuals/member/">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by CyFeng16** [comment]
Misclassification?

**Comment by CyFeng16** [comment]
大分类：AMC or MM or OKR meeting?

**Comment by secortot** [comment]
> 大分类：AMC or MM or OKR meeting?

AMC

**Comment by CyFeng16** [comment]
> > 大分类：AMC or MM or OKR meeting?
> 
> AMC

感觉这种事情是不是不适合放在AMC上说 没有任何学术(paper)信息 ?_?

**Comment by secortot** [comment]
> > > 大分类：AMC or MM or OKR meeting?
> > 
> > 
> > AMC
> 
> 感觉这种事情是不是不适合放在AMC上说 没有任何学术(paper)信息 ?_?
学术指导委员会要在AMC成立呀

**Comment by CyFeng16** [comment]
> > > > 大分类：AMC or MM or OKR meeting?
> > > 
> > > 
> > > AMC
> > 
> > 
> > 感觉这种事情是不是不适合放在AMC上说 没有任何学术(paper)信息 ?_?
> > 学术指导委员会要在AMC成立呀

个人观点不认可这件事情作为poster或oral**出现在paper list中**
留待approbatory的成员approve

**Pull request closed without merging**
