### PR TITLE
📰Poster-Visualizing the Hidden Activity of Artificial Neural Networks

### PR DESCRIPTION
**Pull request by gaojiuy**
> 📰Poster-Visualizing the Hidden Activity of Artificial Neural Networks

<https://github.com/BUPT/ai-ml.club/issues/375>

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:

- [ ] 🗣 Oral (15 MIN)
- [x] 📰 Poster (5 MIN)

## 2. Paper Information

| Paper           | Information                |
| --------------- | -------------------------- |
| Name            | Visualizing the Hidden Activity of Artificial Neural Networks                 |
| Recommendation  |  using dimensionality reduction for two tasks: visualizing the relationships between learned representations of observations, and visualizing the relationships between artificial neurons.    |
| Year            | 2017              |
| Publish         |  IEEE Transactions on Visualization and Computer Graphics ( Volume: 23 , Issue: 1 , Jan. 2017 ) |
| Author          | Paulo E. Rauber, et. al.           |
| Url          | https://ieeexplore.ieee.org/document/7539329                 |

### 3. After Party 🍻

- [ ] 🍻 YES! I'll definitely join the After Party!
- [ ] 🤔 Maybe. I'd like to decide later.
- [x] 🛌 No, I'm afraid not this time.

## 4. New Friend

- [ ] 👥 I'll bring a new friend
- [x] 👤 There's no new friend from me

----------------
<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://ai-ml.club/manuals/member/">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by cgpeter96** [comment]
You should refer the last time CV meeting minutes  `#367`

**Comment by CyFeng16** [comment]
@cgpeter96 You should let the owner merge this PR.

**Comment by cgpeter96** [comment]
image
`S3E8-> S3E10`

**Comment by CyFeng16** [comment]
> image
> `S3E8-> S3E10`

Yeah, you are right!

**Pull request merged**
