### PR TITLE
📰Poster-On PixelWise Explanations for NonLinear Classifier Decisions by LayerWise Relevance Propagation

### PR DESCRIPTION
**Pull request by gaojiuy**
# AMC Seminar Sign Up

> Link to previous seminar meeting minutes issue:

#176 

## 1. Oral / Poster Selection

> Select one of the following selections for Oral or Poster:
>
> 1. Oral should be prepared for _15 - 30_ minutes, and no more than **45** minutes, including Q/A.
> 1. Posters should be prepared for _5 - 10_ minutes, and no more than **15** minutes, including Q/A.

- [ ] 🗣 Oral (15 MIN)
- [x] 📰 Poster (5 MIN)

## 2. Paper Information

> Please fill the follow table and provide all the information as many as possible, for sharing with others better. (delete the rows that you did not fill)

| Paper | Information |
| --- | --- |
| Name | On Pixel-Wise Explanations for Non-Linear Classifier Decisions by Layer-Wise Relevance Propagation |
| Recommendation | Understand and interpret classification models |

### 3. After Party 🍻

> Everyone will be welcome. You can join or not join as you want (not required by the AMC), and change your mind at any time.
>
> 1. After Party will be started right after all the meeting agenda had been fulfilled.
> 1. We will find a bar and drink beers and talk whatever we want. (we can expect that it will be related to meeting topics of the day)
> 1. The bill will be paid AA

- [ ] 🍻 YES! I'll definitely join the After Party!
- [ ] 🤔 Maybe. I'd like to decide later.
- [x] 🛌 No, I'm afraid not this time.

## 4. New Friend

> Whether you have a new friend comes with you to the club.

- [ ] 👥 I'll bring a new friend
- [x] 👤 There's no new friend from me

----------------
<sub>
<i>

Artificial Intelligence & Machine Learning CLUB, 2018 - 2019 <a href="https://ai-ml.club">AI ML Club - AMC</a> <a href="https://ai-ml.club/manuals/member/">Member Manual</a>

</i>
</sub>

### CODE REVIEW

**Comment by gaojiuy** [comment]
@linbo0518  would you please help with this Travis CI error? thanks!
```
# pull request title
not ok 3 Oral or Poster should be started from 🗣 or 📰
  ---
    operator: ok
    expected: true
    actual:   null
    at: Object.<anonymous> (/home/travis/build/BUPT/ai-ml.club/tests/integration.spec.ts:28:13)
    stack: |-
      Error: Oral or Poster should be started from 🗣 or 📰
          at Test.assert [as _assert] (/home/travis/build/BUPT/ai-ml.club/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/travis/build/BUPT/ai-ml.club/node_modules/tape/lib/test.js:77:32)
          at Test.assert (/home/travis/build/BUPT/ai-ml.club/node_modules/tape/lib/test.js:344:10)
          at Test.bound [as true] (/home/travis/build/BUPT/ai-ml.club/node_modules/tape/lib/test.js:77:32)
          at Object.<anonymous> (/home/travis/build/BUPT/ai-ml.club/tests/integration.spec.ts:28:13)
          at Generator.next (<anonymous>)
          at fulfilled (/home/travis/build/BUPT/ai-ml.club/tests/integration.spec.ts:5:58)
          at processTicksAndRejections (internal/process/task_queues.js:85:5)
  ...
# image size should not more than 1MB
```

**Comment by linbo0518** [comment]
PR title should start from 📰, I deleted the space in front of emoji

**Comment by newip** [comment]
> PR title should start from 📰, I deleted the space in front of emoji, but still error

Need to check the travis script. Remove this or correct this checking rule.

**Comment by huan** [comment]
@linbo0518 Travis CI needs another commit to Tigger it run again so that it could be able to update the status of this PR.

**Comment by linbo0518** [comment]
挂靠一波？

**Pull request merged**
