### PR TITLE
add vdeamov profile

### PR DESCRIPTION
**Pull request by VDeamoV**
When pull request, you can create a branch to pull request.(no more annoying commits)

#### step1 ( normally push)
```
git add .
git commit -m "message"
git push
```
#### step2 (pick your commit to branch)
```
git log  # find your commit
git checkout -b patch1 upstream/master # add branch and  link to upstream
git cherry-pick d689c083ac889b1cd09b03857502bb7508ce2cb8 # this is commit-id you find in log
git push origin patch1 # push, then pull request with this branch
```
Happy Coding

### CODE REVIEW

**Comment by linbo0518** [comment]
I think you should change the author to yourself

**Comment by VDeamoV** [comment]
my bad I pull another request

**Comment by huan** [comment]
@VDeamoV You do not need to close a Pull Request if there's any problem.

You can keep committing to your local branch, then the PR will get updated.

**Comment by VDeamoV** [comment]
I will try to reopen it, and fix the commit by just pull request ( It is fun

**Comment by huan** [comment]
Great! We now get another member profile page for AMC, cheers!

**Comment by huan** [comment]
@VDeamoV Did you remember that I had said you will [get a 404 error](https://github.com/BUPT/ai-ml.club/pull/209#pullrequestreview-265576270)?

Now you [get it](https://ai-ml.club/people/VDeamoV/)!

**Comment by VDeamoV** [comment]
@huan Get it, it seems url and author name both should be lower case? I will fix it after back to school. sign~

**Comment by huan** [comment]
Yes, they must be exactly the same!

**Pull request merged**
